// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3SZMtC9yKrPS2LQqNHJKDta5NnW6bks',
    appId: '1:520771909293:web:777d114e7fff3f9a717824',
    messagingSenderId: '124980859440',
    projectId: 'clearvisit-dcbab',
    authDomain: 'clearvisit-dcbab.firebaseapp.com',
    storageBucket: 'clearvisit-dcbab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3SZMtC9yKrPS2LQqNHJKDta5NnW6bks',
    appId: '1:520771909293:android:777d114e7fff3f9a717824',
    messagingSenderId: '124980859440',
    projectId: 'clearvisit-dcbab',
    storageBucket: 'clearvisit-dcbab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-fm55EZ4uaBQoXeecYft5j5qVQ6_jezQ',
    appId: '1:124980859440:ios:a1dd20bfdeb759902013f5',
    messagingSenderId: '124980859440',
    projectId: 'clearvisit-dcbab',
    storageBucket: 'clearvisit-dcbab.firebasestorage.app',
    iosClientId: '124980859440-93hlikit5q9a25ffbjhcas3utf1rm6fq.apps.googleusercontent.com',
    iosBundleId: 'com.clearvisit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-fm55EZ4uaBQoXeecYft5j5qVQ6_jezQ',
    appId: '1:124980859440:macos:a1dd20bfdeb759902013f5',
    messagingSenderId: '124980859440',
    projectId: 'clearvisit-dcbab',
    storageBucket: 'clearvisit-dcbab.firebasestorage.app',
    iosClientId: '124980859440-93hlikit5q9a25ffbjhcas3utf1rm6fq.apps.googleusercontent.com',
    iosBundleId: 'com.clearvisit.app',
  );
} 